### ISSUE TITLE
About the exam3

### ISSUE THREAD

**Issue by RoberBud** [RoberBud/data-engineer-exam#1]
Hello there, I would like to know the purpose of exam 3 for determining the ys in the model, is it a anomaly detection problem? Or I just have to predict the outcome  after a specific time period? Any comments will be much appreciated, thanks!

**Comment by nailo2c** [comment]
Hi @RoberBud , just predict which series data is an anomaly, thanks!

**Comment by nailo2c** [comment]
@RoberBud If you finished the exam, please mention me, thanks!

**Comment by RoberBud** [comment]
@nailo2c  I've finished the exam, thank you very much for providing this chance for me to sharpen my skills,  I really appreciate that, thank you!

**Comment by nailo2c** [comment]
@RoberBud ok, I'll review it later.

**Comment by nailo2c** [comment]
@RoberBud please close this issue, thanks!
