### ISSUE TITLE
improve exam1 algorithm from offline learning to online learning

### ISSUE THREAD

**Issue by nailo2c** [RoberBud/data-engineer-exam#2]
Hi @RoberBud , nice job for exam1, use DBSCAN to find the outlier is elegant.

However, if the data size is huge or data distribution change very fast, maybe the offline learning model would lose its performance.

Please try to improve algorithm.py to the online learning and do not modify my detect function in detector.py.

If have any question, please let me know on the comment, I will reply ASAP.

**Comment by RoberBud** [comment]
OK, I will try to fix that, thank you for your reply!

**Comment by RoberBud** [comment]
@nailo2c I've finished the task, thank you!

**Comment by nailo2c** [comment]
@RoberBud , It is seen that the algorithm can auto-learning the data distribution, good job!
