### ISSUE TITLE
try to improve the performance for exam 2

### ISSUE THREAD

**Issue by nailo2c** [RoberBud/data-engineer-exam#3]
Hi @RoberBud , your code work well.

However, it a little bit slow. Please try to use the *pandas* official method to improve performance.

**Comment by tushar-nitave** [comment]
I will try to fix it.

**Comment by cheyilin** [comment]
Hi @tushar-nitave,

May I ask why you're answering here? Did you take this exam for @RoberBud?

**Comment by tushar-nitave** [comment]
I didn't realize that, it was a open and public issue which I intended to resolve.

**Comment by RoberBud** [comment]
@tushar-nitave Thank you for your reply, but this is an exam so I have to resolve it on my own...
@CheyiLin No, I finished the exam on my own.

**Comment by cheyilin** [comment]
I see, glad we made this clear. 😅

@RoberBud Please follow the suggestion and improve the implementation. Thank you.

**Comment by RoberBud** [comment]
OK, I will try to fix that, thank you!

**Comment by RoberBud** [comment]
I've finished the task, thank you for your suggestion!

**Comment by nailo2c** [comment]
@RoberBud , nice work! Now the performance is much better than the last commit!
