### ISSUE TITLE
exam 3: history data

### ISSUE THREAD

**Issue by nailo2c** [RoberBud/data-engineer-exam#5]
Hi @RoberBud , Could I know why you need to store an object named history, do you have any plan to use those data?

https://github.com/RoberBud/data-engineer-exam/blob/master/exam3/train.py#L74

**Comment by RoberBud** [comment]
It's just for drawing a plot, so I can see the train loss and the val loss. I did a "plot(history['train'])" and "plot(history['val'])" to do this, but I didn't put these statements in the script. Thank you for your reply!

**Comment by nailo2c** [comment]
@RoberBud , got it, nice work!
